# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(max_length=128)),
                ('hire_cost_weekly', models.CharField(max_length=128)),
                ('condition', models.CharField(choices=[('1', 'New'), ('2', 'Excellent'), ('3', 'Good'), ('4', 'Repair'), ('5', 'Discard')], max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='parent',
            name='facebookID',
        ),
        migrations.AddField(
            model_name='parent',
            name='parentof',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
