# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0002_auto_20180530_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='instrument_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
