# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0004_auto_20180530_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Repair', 'Repair'), ('Discard', 'Discard')], max_length=128),
        ),
    ]
