# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lesson', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_content',
            field=models.CharField(max_length=128),
        ),
    ]
